# -*- coding: utf-8 -*-
"""Cópia de Exemplo_Morfologia.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g1MyvkOWSFG6uSsWsexZtHoKiHcCAaJm

Universidade do Vale do Itajaí<br>
Escola do Mar, Ciência e Tecnologia<br>
Professor Felipe Viel

# Exemplo Morfologia

### Tutoriais da OpenCV

- https://docs.opencv.org/master/d9/df8/tutorial_root.html
- https://www.geeksforgeeks.org/opencv-python-tutorial/
"""



#from https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_imgproc/py_morphological_ops/py_morphological_ops.html
import cv2
import numpy as np
#caso for usar o Google Colab com a OpenCV, usar a lib abaixo
from google.colab.patches import cv2_imshow

img = cv2.imread('j.png',0)
img_opening = cv2.imread('j_ruido.png',0)
img_closing = cv2.imread('j_furos.png',0)
altura, largura = img.shape
kernel = np.ones((5,5),np.uint8)
print(kernel)

erosion = cv2.erode(img,kernel,iterations = 2)
dilation = cv2.dilate(img,kernel,iterations = 2)

gradient = cv2.morphologyEx(img, cv2.MORPH_GRADIENT, kernel)
opening = cv2.morphologyEx(img_opening, cv2.MORPH_OPEN, kernel)
closing = cv2.morphologyEx(img_closing, cv2.MORPH_CLOSE, kernel)

'''
#Caso usa com Python no próprio computador
cv2.imshow('in', img)
cv2.imshow('erosion_out', erosion)
cv2.imshow('dilation_out', dilation)
cv2.imshow('opening_out', opening)
cv2.imshow('closing_out', closing)
cv2.imshow('gradient_out', gradient)
'''
#Caso use o Google Colab
cv2_imshow(img)
cv2_imshow(erosion)
cv2_imshow(dilation)
cv2_imshow(opening)
cv2_imshow(closing)
cv2_imshow(gradient)